name: npm pre publish

on:
  push:
    branches:
      - pre-publish

jobs:
  npm-pre-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm i

      - name: Check type
        run: pnpm type:check

      - name: Build
        run: pnpm build

      - name: Prepublish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: pnpm publish --tag next --access public --no-git-checks
